// Regenerates the KU Volleyball launcher icon. Run from a directory with
// playwright installed:  node scripts/make-icons.mjs app/src/main/res
// Generates the KU Volleyball launcher icon: adaptive-icon vector drawables
// plus legacy raster webp for API 24-25 (minSdk is 24, below adaptive icons).
// Rasterizing goes through Chromium's canvas, which can encode webp, so the
// existing .webp filenames stay put and no resource renames are needed.
import { chromium } from 'playwright';
import fs from 'fs';
import path from 'path';

const RES = process.argv[2] || '/workspace/ku-volleyball/app/src/main/res';
const KU_BLUE = '#0051BA';
const WHITE = '#FFFFFF';

// --- Geometry ---------------------------------------------------------------
const C = 54, R = 34, SW = 4, SPAN = 150, RF = 1.25, ROT = 30;
// Endpoints pull in by half the stroke so round caps land exactly on the rim
// instead of poking out as nubs.
const RIM = (R - SW / 2) / R;
const rad = (d) => (d * Math.PI) / 180;
const pt = (a) => [
  (C + R * RIM * Math.cos(rad(a))).toFixed(2),
  (C + R * RIM * Math.sin(rad(a))).toFixed(2),
];
function seamPath(a1) {
  const [x1, y1] = pt(a1), [x2, y2] = pt(a1 + SPAN), r = (R * RF).toFixed(2);
  return `M${x1},${y1} A${r},${r} 0 0,0 ${x2},${y2}`;
}
const SEAMS = [0, 120, 240].map((k) => seamPath(90 + ROT + k));
// Circle as two arcs, for VectorDrawable fills/clips.
const circlePath = (r) =>
  `M${C},${C - r} A${r},${r} 0 1,0 ${C},${C + r} A${r},${r} 0 1,0 ${C},${C - r}Z`;

// --- Vector drawables -------------------------------------------------------
const seamPaths = (color) => SEAMS.map((d) =>
  `    <path
        android:pathData="${d}"
        android:strokeColor="${color}"
        android:strokeWidth="${SW}"
        android:strokeLineCap="round" />`).join('\n');

const vector = (body) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make-icons.mjs — edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${body}
</vector>
`;

const foreground = vector(
  `    <path
        android:pathData="${circlePath(R)}"
        android:fillColor="${WHITE}" />
${seamPaths(KU_BLUE)}`
);

const background = vector(
  `    <path
        android:pathData="M0,0h108v108h-108z"
        android:fillColor="${KU_BLUE}" />`
);

// Themed icons (Android 13+) are tinted by the system, so a filled disc would
// flatten into a blob — line art keeps the ball readable.
const monochrome = vector(
  `    <path
        android:pathData="${circlePath(R - SW / 2)}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="${SW}" />
${seamPaths('#FFFFFF')}`
);

fs.writeFileSync(path.join(RES, 'drawable/ic_launcher_foreground.xml'), foreground);
fs.writeFileSync(path.join(RES, 'drawable/ic_launcher_background.xml'), background);
fs.writeFileSync(path.join(RES, 'drawable/ic_launcher_monochrome.xml'), monochrome);
console.log('wrote 3 vector drawables');

// --- Legacy raster ----------------------------------------------------------
const svg = (shape) => {
  const clip = shape === 'round'
    ? `<circle cx="54" cy="54" r="54"/>`
    : `<rect x="0" y="0" width="108" height="108" rx="20" ry="20"/>`;
  const seams = SEAMS.map((d) =>
    `<path d="${d}" fill="none" stroke="${KU_BLUE}" stroke-width="${SW}" stroke-linecap="round"/>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="108" height="108" viewBox="0 0 108 108">
    <defs><clipPath id="m">${clip}</clipPath></defs>
    <g clip-path="url(#m)"><rect width="108" height="108" fill="${KU_BLUE}"/></g>
    <circle cx="54" cy="54" r="${R}" fill="${WHITE}"/>${seams}</svg>`;
};

const DENSITIES = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage();
await page.setContent('<body style="margin:0"></body>');

for (const [density, size] of Object.entries(DENSITIES)) {
  for (const [file, shape] of [['ic_launcher', 'square'], ['ic_launcher_round', 'round']]) {
    const b64 = await page.evaluate(async ({ markup, size }) => {
      const img = new Image();
      img.src = 'data:image/svg+xml;base64,' + btoa(markup);
      await img.decode();
      const cv = document.createElement('canvas');
      cv.width = cv.height = size;
      const ctx = cv.getContext('2d');
      ctx.drawImage(img, 0, 0, size, size);
      return cv.toDataURL('image/webp', 0.98).split(',')[1];
    }, { markup: svg(shape), size });
    const out = path.join(RES, `mipmap-${density}/${file}.webp`);
    const buf = Buffer.from(b64, 'base64');
    // Guard against a silent PNG fallback if webp encoding were unavailable.
    if (buf.slice(8, 12).toString() !== 'WEBP') throw new Error(`not webp: ${out}`);
    fs.writeFileSync(out, buf);
    console.log(`wrote ${out} (${size}px, ${buf.length}b)`);
  }
}
await browser.close();

// Preview sheet so the result can be eyeballed at real sizes.
fs.writeFileSync('/tmp/claude-0/-home-user-markdown/778cdd4e-264d-5eda-975c-f1e1aaa3913b/scratchpad/icon-preview.html',
  `<body style="background:#2a2a2a;padding:20px;font:12px sans-serif;color:#ddd">
   <div style="display:flex;gap:20px;align-items:flex-end">
   ${Object.entries(DENSITIES).map(([d, s]) =>
    `<figure style="margin:0;text-align:center"><div style="width:${s}px">${svg('square')
      .replace('width="108" height="108"', `width="${s}" height="${s}"`)}</div>
      <figcaption>${d} ${s}px</figcaption></figure>`).join('')}
   ${Object.entries(DENSITIES).map(([d, s]) =>
    `<figure style="margin:0;text-align:center"><div style="width:${s}px">${svg('round')
      .replace('width="108" height="108"', `width="${s}" height="${s}"`)}</div>
      <figcaption>${d} round</figcaption></figure>`).join('')}
   </div></body>`);
console.log('wrote preview sheet');
